"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.attendanceRouter = void 0;
const express_1 = require("express");
const attendance_controller_1 = require("./attendance.controller");
const attendanceRouter = (0, express_1.Router)();
exports.attendanceRouter = attendanceRouter;
attendanceRouter.get('/all-attendance', attendance_controller_1.attendanceController.getAllStudentAttendance);
attendanceRouter.post('/add-attendance/:id', attendance_controller_1.attendanceController.addAttendance);
attendanceRouter.put('/update-attendance/:id/:date', attendance_controller_1.attendanceController.updateAttendance);
