"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.departmentRouter = void 0;
const express_1 = require("express");
const department_controller_1 = require("../controller/department.controller");
const auth_1 = require("../../../middlewear/auth");
const authorization_1 = require("../../../middlewear/authorization");
const departmentRouter = (0, express_1.Router)();
exports.departmentRouter = departmentRouter;
departmentRouter.get('/all-department', auth_1.authentication, authorization_1.authorizationAdmin, department_controller_1.getAllDepartment);
departmentRouter.post('/add-department', auth_1.authentication, authorization_1.authorizationAdmin, department_controller_1.addDepartment);
departmentRouter.put('/update-department/:id', auth_1.authentication, authorization_1.authorizationAdmin, department_controller_1.updateDepartmentById);
departmentRouter.delete('/delete-department/:id', auth_1.authentication, authorization_1.authorizationAdmin, department_controller_1.deleteDepartmentById);
departmentRouter.delete('/deleteall-department', auth_1.authentication, authorization_1.authorizationAdmin, department_controller_1.deleteAllDepartment);
