"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.departmentRouter = void 0;
const express_1 = require("express");
const department_controller_1 = require("../controller/department.controller");
const handlevalidationerror_middlewear_1 = require("../../../middlewear/handlevalidationerror.middlewear");
const departmet_validator_1 = require("../validators/departmet.validator");
const departmentRouter = (0, express_1.Router)();
exports.departmentRouter = departmentRouter;
departmentRouter.get('/all-department', department_controller_1.departmentController.getAllDepartment);
departmentRouter.post('/add-department', ...departmet_validator_1.addDepartmentValidator, handlevalidationerror_middlewear_1.handleValidationErrors, department_controller_1.departmentController.addDepartment);
departmentRouter.put('/update-department/:id', ...departmet_validator_1.updateDepartmentValidator, handlevalidationerror_middlewear_1.handleValidationErrors, department_controller_1.departmentController.updateDepartmentById);
departmentRouter.delete('/delete-department/:id', ...departmet_validator_1.deleteDepartmentValidator, handlevalidationerror_middlewear_1.handleValidationErrors, department_controller_1.departmentController.deleteDepartmentById);
departmentRouter.delete('/deleteall-department', department_controller_1.departmentController.deleteAllDepartment);
