"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.batchRouter = void 0;
const batch_controller_1 = require("./batch.controller");
const express_1 = require("express");
const handlevalidationerror_1 = require("../../middlewear/handlevalidationerror");
const batch_validator_1 = require("./batch.validator");
const batchRouter = (0, express_1.Router)();
exports.batchRouter = batchRouter;
batchRouter.patch('/add-batch', ...batch_validator_1.addBatch, handlevalidationerror_1.handleValidationErrors, batch_controller_1.batchController.addBatch);
batchRouter.get('/get-allbatch', batch_controller_1.batchController.getBatch);
