"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.batchRouter = void 0;
const batch_controller_1 = require("../controller/batch.controller");
const express_1 = require("express");
const authorization_1 = require("../../../middlewear/authorization");
const auth_1 = require("../../../middlewear/auth");
const batchRouter = (0, express_1.Router)();
exports.batchRouter = batchRouter;
batchRouter.post('/add-batch', auth_1.authentication, authorization_1.authorizationAdmin, batch_controller_1.addBatch);
batchRouter.get('/get-allbatch', auth_1.authentication, authorization_1.authorizationAdmin, batch_controller_1.getBatch);
