"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.attendanceRouter = void 0;
const express_1 = require("express");
const attendance_controller_1 = require("../controller/attendance.controller");
const auth_1 = require("../../../middlewear/auth");
const attendanceRouter = (0, express_1.Router)();
exports.attendanceRouter = attendanceRouter;
attendanceRouter.get('/all-attendance', auth_1.authentication, attendance_controller_1.getAllStudentAttendance);
attendanceRouter.post('/update-attendance/:id', auth_1.authentication, attendance_controller_1.updateAttendance);
