"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminRouter = void 0;
const express_1 = require("express");
const admin_controller_1 = require("../controller/admin.controller");
const adminRouter = (0, express_1.Router)();
exports.adminRouter = adminRouter;
adminRouter.post('/login');
adminRouter.post('/signup', admin_controller_1.signUp);
adminRouter.post('/logout');
adminRouter.post('/logoutall');
