"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.studentRouter = void 0;
const express_1 = require("express");
const student_controller_1 = require("../controller/student.controller");
const auth_1 = require("../../../middlewear/auth");
const studentRouter = (0, express_1.Router)();
exports.studentRouter = studentRouter;
studentRouter.get('/all-students', auth_1.authentication, student_controller_1.getAllStudent);
studentRouter.post('/add-student', auth_1.authentication, student_controller_1.addStudent);
studentRouter.put('/update-student/:id', auth_1.authentication, student_controller_1.updateStudentById);
studentRouter.delete('/delete-student/:id', auth_1.authentication, student_controller_1.deleteStudentById);
studentRouter.delete('/deleteall-students', auth_1.authentication, student_controller_1.deleteAllStudents);
