"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.studentRouter = void 0;
const express_1 = require("express");
const student_controller_1 = require("./student.controller");
const handlevalidationerror_1 = require("../../middlewear/handlevalidationerror");
const student_validator_1 = require("./student.validator");
const studentRouter = (0, express_1.Router)();
exports.studentRouter = studentRouter;
studentRouter.get('/all-students', student_controller_1.studentController.getAllStudent);
studentRouter.get('/getanalytics', student_controller_1.studentController.getAnalyticsData);
studentRouter.get('/vacantseats', student_controller_1.studentController.getVacantSeats);
studentRouter.get('/presentlessthan75', student_controller_1.studentController.presentLessThan75);
studentRouter.get('/absent/:date', ...student_validator_1.getAbsentOnDate, handlevalidationerror_1.handleValidationErrors, student_controller_1.studentController.getAbsentStudents);
studentRouter.post('/add-student', ...student_validator_1.addStudentValidator, handlevalidationerror_1.handleValidationErrors, student_controller_1.studentController.addStudent);
studentRouter.put('/update-student/:id', ...student_validator_1.updateStudentValidator, handlevalidationerror_1.handleValidationErrors, student_controller_1.studentController.updateStudentById);
studentRouter.delete('/delete-student/:id', ...student_validator_1.deleteStudentByIdValidator, handlevalidationerror_1.handleValidationErrors, student_controller_1.studentController.deleteStudentById);
studentRouter.delete('/deleteall-students', student_controller_1.studentController.deleteAllStudents);
